Game
misselliev/tic-tac-js pull request #1
Opened 2019-10-08 16:40 UTC by stiakov

2019-10-09 23:50 UTC, JamesOkunlade requested changes
### Hello, devs ✋ Nice work on the Tic-Tac-Toe game 👏 😄 . There are some things you'll need to improve on though.

**This project follows the lesson about Factory Functions and The Module Pattern so the main goal is to put into practice those concepts along with the main concepts of Object-Oriented Programming.** 

- Separate your code into different files and modules say `display/dom-manager`, `player`, `gameboard` and `play` and use `es6 import/export` to require each file in the other.
- Keep all dom related tasks in the `display/dom-manager` and don't mix it with the game logic.
- Change all your classic functions to `ES6 arrow functions`.
  
**Fix those points and request for re-review.**

**Status: `Changes required`**

Happy coding 😎

2019-10-09 23:50 UTC, JamesOkunlade commented on js/index.js
> +// };
Please delete this. Don't leave unused code as a comment in your code.

2019-10-09 23:50 UTC, JamesOkunlade commented on js/index.js
> +  function turn(cellId) {
Always use the `ES6 arrow function`

2019-10-09 23:50 UTC, JamesOkunlade commented on js/index.js
> +  function turnClick(cell) {
Use `arrow function`

2019-10-11 18:56 UTC, AdnanAfsari approved these changes
Hello @stiakov @misselliev ✋ 

Nice work, its a 👍 form me.

**Status : Approved**

Happy Coding

2019-10-11 19:09 UTC, merged